apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy-v2
  namespace: webapp-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: 537380924761.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:latest
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.mysql-ns.svc.cluster.local"
            - name: DBUSER
              value: "root"
            - name: DBPWD
              value: "rootpass"
            - name: DBPORT
              value: "3306"
      imagePullSecrets:
        - name: ecr-creds
