apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy-mysql
  namespace: mysql-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 537380924761.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: ecr-creds
